FROM oven/bun:1 AS build

WORKDIR /app

COPY .next/standalone ./.next/standalone
COPY .next/static ./.next/standalone/.next/static
COPY public ./.next/standalone/public
COPY node_modules node_modules

CMD ["bun", "run", "./.next/standalone/server.js"]
