name: Build

on:
    push:
        branches:
            - 'main'
        tags:
            - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Restore Turborepo cache
              uses: actions/cache@v4
              with:
                  path: .turbo
                  key: ${{ runner.os }}-turbo-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-turbo-

            - name: Set up Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: |
                  bun install --frozen-lockfile

            - name: Build
              run: |
                  bun --bun run build

            - name: Upload backend artifact
              uses: actions/upload-artifact@v4
              with:
                  name: backend-${{ runner.os }}-${{ runner.arch }}
                  path: |
                      apps/backend/dist/

            - name: Upload web artifact
              uses: actions/upload-artifact@v4
              with:
                  name: web-${{ runner.os }}-${{ runner.arch }}
                  path: |
                      apps/web/.next/
                      !apps/web/.next/cache

    docker:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Dockerfile
              uses: actions/checkout@v4
              with:
                  path: hetu
                  sparse-checkout: |
                      Dockerfile.*
                  sparse-checkout-cone-mode: false

            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                  pattern: '*-${{ runner.os }}-${{ runner.arch }}'

            - name: Display structure of downloaded files
              run: ls -R

            - name: Docker meta
              id: meta-backend
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository_owner }}/hetu-backend
                  # generate Docker tags based on the following events/attributes
                  tags: |
                      type=ref,event=branch
                      type=semver,pattern={{version}}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GHCR
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build backend and push
              uses: docker/build-push-action@v6
              with:
                  file: hetu/Dockerfile.package-backend
                  context: backend-${{ runner.os }}-${{ runner.arch }}
                  tags: ${{ steps.meta-backend.outputs.tags }}
                  labels: ${{ steps.meta-backend.outputs.labels }}
